/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var g=Object.getOwnPropertyNames;var m=Object.prototype.hasOwnProperty;var d=(a,e)=>{for(var i in e)o(a,i,{get:e[i],enumerable:!0})},u=(a,e,i,t)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of g(e))!m.call(a,s)&&s!==i&&o(a,s,{get:()=>e[s],enumerable:!(t=p(e,s))||t.enumerable});return a};var h=a=>u(o({},"__esModule",{value:!0}),a);var v={};d(v,{default:()=>n});module.exports=h(v);var c=require("obsidian"),n=class extends c.Plugin{async onload(){this.registerDomEvent(document,"click",async e=>{var i;try{let t=e.target;if(!t||!((i=t.parentElement)!=null&&i.classList.contains("is-unresolved")))return;let l=`${this.app.workspace.getActiveFile().path.split("/").slice(0,-1).join("/")}/${t.innerText}.md`,r=await this.app.vault.create(l,"");await this.app.workspace.getLeaf().openFile(r)}catch(t){let s="Error in 'Current Directory New Note' plugin";t!=null&&t.message&&(s+=": "+t.message),new c.Notice(s)}})}};
