/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var g=(a,t)=>{for(var e in t)o(a,e,{get:t[e],enumerable:!0})},m=(a,t,e,s)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of d(t))!h.call(a,i)&&i!==e&&o(a,i,{get:()=>t[i],enumerable:!(s=p(t,i))||s.enumerable});return a};var u=a=>m(o({},"__esModule",{value:!0}),a);var v={};g(v,{default:()=>n});module.exports=u(v);var c=require("obsidian"),n=class extends c.Plugin{async onload(){this.registerDomEvent(document,"click",async t=>{try{let e=t.target;if(!e||!e.classList.contains("cm-underline"))return;let s=e.innerText;if(this.app.metadataCache.getFirstLinkpathDest(s,""))return;let r=`${this.app.workspace.getActiveFile().path.split("/").slice(0,-1).join("/")}/${s}.md`,l=await this.app.vault.create(r,"");await this.app.workspace.getLeaf().openFile(l)}catch(e){let s="Error in 'Current Directory New Note' plugin";e!=null&&e.message&&(s+=": "+e.message),new c.Notice(s)}})}};
